apiVersion: v1
kind: Service
metadata:
  name: chords-and-beats
  labels:
    app: chords-and-beats
    tier: frontend
spec:
  type: NodePort
  selector:
    app: chords-and-beats
    tier: frontend
  ports:
    - port: 80